name: Vitaminails
author: Natalia Carena
description: En Vitaminails ofrecemos servicios de manicuria y pedicuria, nos especializamos por ofrecer servicios de uñas acrilicas, uñas gelish y uñas francesas.
site-info: Belleza para tus manos y pies
avatar: /images/vitaminails-unas-acrilicas-unas-gelish.png

#
# Flags below are optional
#

# Variables de Vitaminails:
whatsappurl: https://wa.me/5219841969530?text=Hola%20Natalia%20%F0%9F%91%8B!%20Te%20escribo%20desde%20la%20p%C3%A1gina%20de%20contacto%20de%20Vitaminails.com.


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: citas@vitaminails.com
  facebook: vitaminails
  flickr:
  github: 
  instagram: vitaminails
  linkedin: 
  pinterest: vitaminails
  rss: rss
  twitter: vitaminails
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: true

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: http://vitaminails.com
enforce_ssl: https://vitaminails.com

nocover: /images/og-image.jpg

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:categories/:title

# The release of Jekyll Now that you're using
version: v1.2.0


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

include: ['_pages']

paginate: 6
paginate_path: /pagina-:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME